// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200217142647");
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_row", "crow2");
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_us", "cus2n");
user_pref("app.normandy.startupExperimentPrefs.privacy.annotate_channels.strict_list.enabled", false);
user_pref("app.normandy.startupExperimentPrefs.urlclassifier.trackingAnnotationTable.testEntries", "etp-experiment-2.dummytracker.org");
user_pref("app.normandy.user_id", "b893a0ce-0fca-480d-8dbe-184bf3eed30a");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1582891299);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1582891539);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1582891419);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1582891329);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.E7CF176E110C211B", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 10337);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1582891268);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 91);
user_pref("browser.newtabpage.activity-stream.impressionId", "{9beac058-69b0-4200-9a16-c74f68c73d1b}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1582891308937");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1582893105937");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1582891274176");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1582894874176");
user_pref("browser.search.region", "MA");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 7068);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200217142647");
user_pref("browser.startup.homepage_override.mstone", "73.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1582891270);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"_531906d3-e22f-4a6c-a102-8057b88a1a63_-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"_531906d3-e22f-4a6c-a102-8057b88a1a63_-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1582891271403");
user_pref("devtools.selfxss.count", 100);
user_pref("devtools.toolbox.selectedTool", "webconsole");
user_pref("devtools.toolsidebar-height.inspector", 350);
user_pref("devtools.toolsidebar-width.inspector", 700);
user_pref("devtools.toolsidebar-width.inspector.splitsidebar", 350);
user_pref("devtools.webextensions.{531906d3-e22f-4a6c-a102-8057b88a1a63}.enabled", true);
user_pref("distribution.iniFile.exists.appversion", "73.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "ee948fe18d134d0cbc4fa2dd43b5dccf");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "73.0.1");
user_pref("extensions.lastPlatformVersion", "73.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{531906d3-e22f-4a6c-a102-8057b88a1a63}", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"e252bd26-1f3f-4d1c-8d63-2f61341f8a7c\",\"formautofill@mozilla.org\":\"8383e68a-d3df-4bb1-986a-2ae841f98715\",\"screenshots@mozilla.org\":\"1c45f4de-cfa5-4210-80f6-bd18d10f75a8\",\"webcompat-reporter@mozilla.org\":\"d80e374b-271e-455f-98a6-70e98f4f819a\",\"webcompat@mozilla.org\":\"8ed5cdcb-1a91-4eb9-8271-8ed60a6a87f0\",\"default-theme@mozilla.org\":\"8ba81ef6-1daf-4d5c-8c75-aaaab1bd5f6d\",\"google@search.mozilla.org\":\"c906d7f6-0803-4c5d-95b8-c73b90d353f1\",\"bing@search.mozilla.org\":\"5ee391b1-75a3-4500-8516-2b3bef07bc0c\",\"amazon@search.mozilla.org\":\"62d0bbad-0be6-494a-b28b-51c69311b94a\",\"ddg@search.mozilla.org\":\"ca113936-0391-4c92-9f9f-feb5c529dc93\",\"ebay@search.mozilla.org\":\"f71159de-2aa7-4122-8723-43c3a629fff7\",\"qwant@search.mozilla.org\":\"cb9b5e89-eb50-45bb-a6ee-5ae59276b1ad\",\"wikipedia@search.mozilla.org\":\"ffaf2a38-acbe-4fa1-8e49-fd581c7703ab\",\"{531906d3-e22f-4a6c-a102-8057b88a1a63}\":\"506f0da6-a003-4f08-9ceb-c342eaba7110\"}");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "73.0.1");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x0152");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "10.18.10.5059");
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x0152");
user_pref("sanity-test.driver-version", "10.18.10.5059");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20200217142647");
user_pref("security.sandbox.content.tempDirSuffix", "{82ecbadc-7b8b-4c7a-b5f2-362af94e2124}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{8ad68681-2788-4669-b022-86fb264a4d5c}");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1582891262);
user_pref("toolkit.telemetry.cachedClientID", "c0412a74-511b-41be-844b-b7e51f748cb5");
user_pref("toolkit.telemetry.previousBuildID", "20200217142647");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
