// Generated by Selenium IDE
const {Builder, By, Key, until} = require('selenium-webdriver')
const firefox = require('selenium-webdriver/firefox')
const options = new firefox.Options()
options.setProfile('seleiumProfileFirefox')
const assert = require('assert')
const proxy = require('selenium-webdriver/proxy')
const fs = require('fs');
let login  = "";
let pass   = "";
try {



        let data = fs.readFileSync('docs/doc.txt', 'utf8');

        //convert data to array
        list = data.split('\n');
         let info = list[0].split('/');

        let url = "/";
         login  = info[0];
         pass   = info[1];


        // fs.unlinkSync("emails/"+file);

} catch (e) {

    console.log('Error:', e.stack);
}

describe('idrive', function (done) {
    this.timeout(0);
    let driver;
    let elm;
    beforeEach(async function () {


        driver = await new Builder()
            .forBrowser('firefox')
            .setFirefoxOptions(options)
            .build();

    });
    afterEach(async function () {



    })
    it('idrive', async function () {

                 await driver.get("https://affiliate.rembrow.com/");
                 await driver.executeScript(
                        "var span = document.createElement('h1');"+
                        "span.setAttribute('id','test');" +
                        "span.style.position = 'absolute';" +
                        "span.style.left = '50%';" +
                        "span.style.top ='50%';" +
                        "span.style.transform ='translate(-50%,-50%)';" +
                        "span.style.zIndex ='1000';" +
                        "span.innerText ='waiting to log In ...';" +
                        "document.querySelector('#mainContainer').before(span);" +
                        "document.querySelector('#mainContainer').style.filter = 'blur(5px)';");
                 await driver.sleep(1000);
                 await driver.executeScript("document.querySelector('#uname').value = '"+login+"';document.querySelector('#pword').value = '"+pass+"';document.querySelector('.btn.login_button').click()")
                 await fs.unlinkSync("docs/doc.txt")

    })

})

